---
title: "strings_and_factors.Rmd"
author: "Ruilian Zhang"
date: "10/21/2021"
output: github_document
---

```{r}
library(tidyverse)
library(rvest)
library(p8105.datasets)
```


## String vectors

```{r}
string_vec = c("my", "name", "is", "jeff")

str_detect(string_vec, "m") 
str_detect(string_vec, "Jeff")# case sensitive

str_replace(string_vec, "jeff", "Jeff")
str_replace(string_vec, "e", "this is a upper case E")
str_replace(string_vec, "jeff", "")
```

```{r}
string_vec = c(
  "i think we all rule for participating",
  "i think i have been caught",
  "i think this will be quite fun actually",
  "it will be fun, i think"
  )

str_detect(string_vec, "i think")
str_detect(string_vec, "^i think") # ^ represents the beginning of the line
str_detect(string_vec, "i think$") # $ the end of the line
```

```{r}
string_vec = c(
  "Y'all remember Pres. HW Bush?",
  "I saw a green bush",
  "BBQ and Bushwalking at Molonglo Gorge",
  "BUSH -- LIVE IN CONCERT!!"
  )

str_detect(string_vec, "bush")
str_detect(string_vec, "Bush")
str_detect(string_vec, "[Bb]ush")
```

```{r}
string_vec = c(
  '7th inning stretch',
  '1st half soon to begin. Texas won the toss.',
  'she is 5 feet 4 inches tall',
  '3AM - cant sleep :('
  )

str_detect(string_vec, "[0-9][a-zA-Z]")
```

```{r}
string_vec = c(
  'Its 7:11 in the evening',
  'want to go to 7-11?',
  'my flight is AA711',
  'NetBios: scanning ip 203.167.114.66'
  )

str_detect(string_vec, "7.11") # exact match
```

```{r}
string_vec = c(
  'The CI is [2, 5]',
  ':-]',
  ':-[',
  'I found the answer on pages [6-7]'
  )

str_detect(string_vec, "\\[")
```


## Why factors are wierd

```{r}
factor_vec = factor(c("male", "male", "female", "female"))
as.numeric(factor_vec) # 2 for second level and 1 for first level

factor_vec = fct_relevel(factor_vec, "male") # change levels
as.numeric(factor_vec)
```


## NSDUH

```{r}
nsduh_url = "http://samhda.s3-us-gov-west-1.amazonaws.com/s3fs-public/field-uploads/2k15StateFiles/NSDUHsaeShortTermCHG2015.htm"

table_marj = 
  read_html(nsduh_url) %>% 
  html_table() %>% 
  first() %>% 
  slice(-1)
```

Let's clean this up!

```{r}
marj_df = 
  table_marj %>% 
  select(-contains("P Value")) %>% 
  pivot_longer(
    -State,
    names_to = "age_year",
    values_to = "percent"
  ) %>% 
  separate(age_year, into = c("age", "year"), "\\(") %>% 
  mutate(
    year = str_replace(year, "\\)", ""),
    percent = str_replace(percent, "[a-c]$", ""),
    percent = as.numeric(percent)
  ) %>% 
  filter(!(State %in% c("Total U.S.", "Northeast", "Midwest", "South", "West")))
```

Do dataframe stuff

```{r}
marj_df %>% 
  filter(age == "12-17") %>% 
  mutate(
    State = fct_reorder(State, percent)
  ) %>% 
  ggplot(aes(x = State, y = percent, color = year)) +
  geom_point() +
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust = 1)) # angle = 90 rotate x tick labels
```


## Resturant inspections

```{r}
data("rest_inspec")
```

```{r}
#rest_inspec %>% 
  #janitor::tabyl(boro, grade)

rest_inspec %>% 
  group_by(boro, grade) %>% 
  summarize(n = n()) %>% 
  pivot_wider(names_from = grade, values_from = n)
```

```{r}
rest_inspec =
  rest_inspec %>% 
  filter(
    str_detect(grade, "[ABC]"), # or: grade %in% c("A", "B", "C")
    boro != "Missing"
      ) %>% 
  mutate(boro = str_to_title(boro)) # make first letter upper case
```


```{r}
rest_inspec %>% 
  filter(str_detect(dba, "[Pp][Ii][Zz][Zz][Aa]")) %>% 
  group_by(boro, grade) %>% 
  summarize(n = n()) %>% 
  pivot_wider(names_from = grade, values_from = n)
```


```{r}
rest_inspec %>% 
  filter(str_detect(dba, "[Pp][Ii][Zz][Zz][Aa]")) %>%
  ggplot(aes(x = boro, fill = grade)) + 
  geom_bar() 
```

```{r}
rest_inspec %>% 
  filter(str_detect(dba, "[Pp][Ii][Zz][Zz][Aa]")) %>%
  mutate(boro = fct_infreq(boro)) %>% # order by number of pizza places
  ggplot(aes(x = boro, fill = grade)) + 
  geom_bar()
```


```{r}
rest_inspec %>% 
  filter(str_detect(dba, "[Pp][Ii][Zz][Zz][Aa]")) %>%
  mutate(boro = fct_infreq(boro),
         boro = str_replace(boro, "Manhattan", "The City")) %>% # didn't work - change order 
  ggplot(aes(x = boro, fill = grade)) +
  geom_bar()
```

```{r}
rest_inspec %>% 
  filter(str_detect(dba, "[Pp][Ii][Zz][Zz][Aa]")) %>%
  mutate(boro = fct_infreq(boro),
         boro = fct_recode(boro, "The City" = "Manhattan")) %>% # a dedicated function for renaming factor levels
  ggplot(aes(x = boro, fill = grade)) +
  geom_bar()
```

